name: nilelon
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bot_toast: ^4.1.3
  dio: ^5.4.3+1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  shimmer: ^3.0.0
  get_it: ^7.7.0
  iconsax: ^0.0.8
  gradient_icon: ^2.0.9
  svg_flutter: ^0.0.1
  gradient_borders: ^1.0.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  flutter_slidable: ^3.1.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  month_picker_dialog: ^4.0.0
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  flutter_custom_clippers: ^2.1.0
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  pdf: ^3.11.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_screenutil: ^5.9.3
  sizer: ^2.0.15
  dartz: ^0.10.1
  jwt_decoder: ^2.0.1
  freezed_annotation: ^2.4.4
  google_sign_in: ^6.2.1
  retrofit: ^4.1.0
  flutter_braintree: ^4.0.0
  signalr_core: ^1.1.1
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.2
  flutter_local_notifications: ^17.2.3
  device_preview: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  freezed: ^2.5.2
  retrofit_generator: ^8.1.2
  mockito: ^5.4.4
  intl_utils: ^2.8.7
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/app_logo.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/images/app_logo.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/images/app_logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/app_logo.png
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_10pt-Regular.ttf
    - family: Londrina Solid
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
flutter_intl:
  enabled: true


flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
